[package]
name = "Hippo"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
eframe = "0.28.1"
env_logger = "0.11.5"
ndarray = "0.16.0"
slotmap = { version = "1.0" }
num-traits = "0.2"